
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '9C9C9627D8DDBEB3C34601366CAAA9C1'
    
_lr_action_items = {'FLOATLITERAL':([43,58,61,62,67,68,76,77,79,88,89,90,92,95,97,108,],[-66,-66,-41,-66,-44,82,-40,-57,-66,-56,-59,-43,-66,-58,-41,-66,]),'$end':([1,15,],[0,-1,]),'IDENTIFIER':([2,4,12,13,14,19,22,29,30,31,32,33,34,36,37,38,39,40,41,42,43,44,45,46,48,51,52,55,56,57,58,59,60,61,62,65,66,67,68,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,92,93,95,96,97,101,107,108,109,110,],[4,-2,-11,4,-10,4,-10,-66,4,-5,4,-66,-6,4,4,-9,-30,-29,-34,-32,-66,-28,-33,-27,-31,4,-4,-13,-15,4,-66,4,-38,-41,-66,-14,-39,-44,4,-66,-35,-7,-8,-40,-57,-42,-66,-46,-45,-55,-54,-53,-36,-66,4,-56,-59,-43,-66,4,-58,-52,-41,-47,-65,-66,-60,4,]),'OPERATORS':([4,16,17,18,20,21,23,24,25,26,28,31,33,34,37,38,39,40,41,42,43,44,45,46,47,48,50,51,52,54,55,56,57,58,59,60,61,62,63,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,87,88,89,90,91,92,94,95,96,97,98,99,101,102,103,104,107,108,109,111,113,],[-2,17,-66,-17,-66,27,-18,-20,-66,-16,-19,-5,-66,-6,-66,-9,-30,-29,-34,-32,59,-28,-33,-27,-26,-31,62,-66,-4,64,-13,-15,-66,-66,-66,-38,-41,-66,-25,-14,77,-44,79,-64,85,86,-66,-35,-7,-8,-40,88,89,-66,-46,-45,-55,-54,92,-36,-66,-56,95,-43,96,-66,-63,-58,-52,-41,101,104,-47,-51,-48,108,-65,-66,-60,104,-50,]),'INTLITERAL':([43,58,61,62,67,68,76,77,79,88,89,90,92,95,97,108,],[-66,-66,-41,-66,-44,83,-40,-57,-66,-56,-59,-43,-66,-58,-41,-66,]),'STRINGLITERAL':([64,],[75,]),'KEYWORDS':([0,3,4,5,6,7,8,9,10,11,17,20,23,25,27,29,31,32,33,34,35,37,38,39,40,41,42,44,45,46,47,48,49,51,52,53,55,56,57,59,60,63,65,66,72,73,74,75,78,80,81,82,83,84,85,86,87,93,96,100,101,105,106,107,109,110,112,],[2,5,-2,9,9,-3,-22,14,15,-21,22,22,-18,22,29,36,-5,43,36,-6,53,-66,-9,-30,-29,-34,-32,-28,-33,-27,-26,-31,-24,43,-4,-23,-13,-15,-66,72,-38,-25,-14,-39,36,-35,-7,-8,-42,-46,-45,-55,-54,-53,-36,36,43,43,-52,107,-47,-62,109,36,-60,43,-61,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'assign_stmt':([32,51,87,93,110,],[39,39,39,39,39,]),'postfix_expr':([68,],[78,]),'return_stmt':([32,51,87,93,110,],[45,45,45,45,45,]),'call_expr':([68,],[80,]),'assign_expr':([32,51,87,93,110,],[41,41,41,41,41,]),'any_type':([9,],[13,]),'decl':([29,33,72,86,107,],[32,52,87,93,110,]),'write_stmt':([32,51,87,93,110,],[42,42,42,42,42,]),'cond':([59,],[71,]),'func_decl':([5,6,],[6,6,]),'if_stmt':([32,51,87,93,110,],[44,44,44,44,44,]),'str':([64,],[74,]),'pgm_body':([5,],[10,]),'string_decl':([29,33,72,86,107,],[33,33,33,33,33,]),'factor_prefix':([58,],[68,]),'param_decl_tail':([20,25,],[26,28,]),'read_stmt':([32,51,87,93,110,],[48,48,48,48,48,]),'id_list':([30,59,],[38,70,]),'addop':([66,],[76,]),'func_body':([29,],[35,]),'stmt_list':([32,51,87,93,110,],[49,63,94,100,112,]),'else_part':([100,],[106,]),'factor':([58,],[66,]),'var_type':([9,17,20,25,29,33,72,86,107,],[12,19,19,19,30,30,30,30,30,]),'expr_prefix':([43,62,79,92,108,],[58,58,58,58,58,]),'var_decl':([29,33,72,86,107,],[31,31,31,31,31,]),'param_decl':([17,20,25,],[20,25,25,]),'while_stmt':([32,51,87,93,110,],[40,40,40,40,40,]),'expr_list_tail':([99,111,],[103,113,]),'id_tail':([37,57,],[55,65,]),'param_decl_list':([17,],[21,]),'expr':([43,62,79,92,108,],[60,73,91,99,111,]),'mulop':([78,],[90,]),'primary':([68,],[81,]),'func_declarations':([5,6,],[7,11,]),'base_stmt':([32,51,87,93,110,],[46,46,46,46,46,]),'empty':([5,6,17,20,25,29,32,33,37,43,51,57,58,59,62,72,79,86,87,92,93,99,100,107,108,110,111,],[8,8,18,24,24,34,47,34,56,61,47,56,67,69,61,34,61,34,47,97,47,102,105,34,61,47,102,]),'expr_list':([92,],[98,]),'id':([2,13,19,30,32,36,37,51,57,59,68,87,93,110,],[3,16,23,37,50,54,57,50,57,37,84,50,50,50,]),'program':([0,],[1,]),'stmt':([32,51,87,93,110,],[51,51,51,51,51,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> KEYWORDS id KEYWORDS pgm_body KEYWORDS','program',5,'p_program_program','parser.py',12),
  ('id -> IDENTIFIER','id',1,'p_program_idea','parser.py',15),
  ('pgm_body -> func_declarations','pgm_body',1,'p_program_pgm_body','parser.py',18),
  ('decl -> string_decl decl','decl',2,'p_program_decl','parser.py',21),
  ('decl -> var_decl','decl',1,'p_program_decl','parser.py',22),
  ('decl -> empty','decl',1,'p_program_decl','parser.py',23),
  ('string_decl -> KEYWORDS id OPERATORS str','string_decl',4,'p_gstring_string_decl','parser.py',28),
  ('str -> STRINGLITERAL','str',1,'p_gstring_str','parser.py',31),
  ('var_decl -> var_type id_list','var_decl',2,'p_variables_var_decl','parser.py',36),
  ('var_type -> KEYWORDS','var_type',1,'p_variables_var_type','parser.py',39),
  ('any_type -> var_type','any_type',1,'p_variables_any_type','parser.py',42),
  ('any_type -> KEYWORDS','any_type',1,'p_variables_any_type','parser.py',43),
  ('id_list -> id id_tail','id_list',2,'p_variables_id_list','parser.py',46),
  ('id_tail -> id id_tail','id_tail',2,'p_variables_id_tail','parser.py',49),
  ('id_tail -> empty','id_tail',1,'p_variables_id_tail','parser.py',50),
  ('param_decl_list -> param_decl param_decl_tail','param_decl_list',2,'p_fparams_param_decl_list','parser.py',55),
  ('param_decl_list -> empty','param_decl_list',1,'p_fparams_param_decl_list','parser.py',56),
  ('param_decl -> var_type id','param_decl',2,'p_fparams_param_decl','parser.py',59),
  ('param_decl_tail -> param_decl param_decl_tail','param_decl_tail',2,'p_fparams_param_decl_tail','parser.py',62),
  ('param_decl_tail -> empty','param_decl_tail',1,'p_fparams_param_decl_tail','parser.py',63),
  ('func_declarations -> func_decl func_declarations','func_declarations',2,'p_fdecl_func_declarations','parser.py',68),
  ('func_declarations -> empty','func_declarations',1,'p_fdecl_func_declarations','parser.py',69),
  ('func_decl -> KEYWORDS any_type id OPERATORS param_decl_list OPERATORS KEYWORDS func_body KEYWORDS','func_decl',9,'p_fdecl_func_decl','parser.py',72),
  ('func_body -> decl stmt_list','func_body',2,'p_fdecl_func_body','parser.py',75),
  ('stmt_list -> stmt stmt_list','stmt_list',2,'p_statements_stmt_list','parser.py',80),
  ('stmt_list -> empty','stmt_list',1,'p_statements_stmt_list','parser.py',81),
  ('stmt -> base_stmt','stmt',1,'p_statements_stmt','parser.py',84),
  ('stmt -> if_stmt','stmt',1,'p_statements_stmt','parser.py',85),
  ('stmt -> while_stmt','stmt',1,'p_statements_stmt','parser.py',86),
  ('base_stmt -> assign_stmt','base_stmt',1,'p_statements_base_stmt','parser.py',89),
  ('base_stmt -> read_stmt','base_stmt',1,'p_statements_base_stmt','parser.py',90),
  ('base_stmt -> write_stmt','base_stmt',1,'p_statements_base_stmt','parser.py',91),
  ('base_stmt -> return_stmt','base_stmt',1,'p_statements_base_stmt','parser.py',92),
  ('assign_stmt -> assign_expr','assign_stmt',1,'p_basic_assign_stmt','parser.py',96),
  ('assign_expr -> id OPERATORS expr','assign_expr',3,'p_basic_assign_expr','parser.py',99),
  ('read_stmt -> KEYWORDS OPERATORS id_list OPERATORS','read_stmt',4,'p_basic_read_stmt','parser.py',102),
  ('write_stmt -> KEYWORDS OPERATORS id_list OPERATORS','write_stmt',4,'p_basic_write_stmt','parser.py',105),
  ('return_stmt -> KEYWORDS expr','return_stmt',2,'p_basic_return_stmt','parser.py',108),
  ('expr -> expr_prefix factor','expr',2,'p_expressions_expr','parser.py',114),
  ('expr_prefix -> expr_prefix factor addop','expr_prefix',3,'p_expressions_expr_prefix','parser.py',117),
  ('expr_prefix -> empty','expr_prefix',1,'p_expressions_expr_prefix','parser.py',118),
  ('factor -> factor_prefix postfix_expr','factor',2,'p_expressions_factor','parser.py',121),
  ('factor_prefix -> factor_prefix postfix_expr mulop','factor_prefix',3,'p_expressions_factor_prefix','parser.py',124),
  ('factor_prefix -> empty','factor_prefix',1,'p_expressions_factor_prefix','parser.py',125),
  ('postfix_expr -> primary','postfix_expr',1,'p_expressions_postfix_expr','parser.py',128),
  ('postfix_expr -> call_expr','postfix_expr',1,'p_expressions_postfix_expr','parser.py',129),
  ('call_expr -> id OPERATORS expr_list OPERATORS','call_expr',4,'p_expressions_call_expr','parser.py',132),
  ('expr_list -> expr expr_list_tail','expr_list',2,'p_expressions_expr_list','parser.py',135),
  ('expr_list -> empty','expr_list',1,'p_expressions_expr_list','parser.py',136),
  ('expr_list_tail -> OPERATORS OPERATORS expr expr_list_tail','expr_list_tail',4,'p_expressions_expr_list_tail','parser.py',139),
  ('expr_list_tail -> empty','expr_list_tail',1,'p_expressions_expr_list_tail','parser.py',140),
  ('primary -> OPERATORS expr OPERATORS','primary',3,'p_expressions_primary','parser.py',143),
  ('primary -> id','primary',1,'p_expressions_primary','parser.py',144),
  ('primary -> INTLITERAL','primary',1,'p_expressions_primary','parser.py',145),
  ('primary -> FLOATLITERAL','primary',1,'p_expressions_primary','parser.py',146),
  ('addop -> OPERATORS OPERATORS','addop',2,'p_expressions_addop','parser.py',149),
  ('addop -> OPERATORS','addop',1,'p_expressions_addop','parser.py',150),
  ('mulop -> OPERATORS OPERATORS','mulop',2,'p_expressions_mulop','parser.py',153),
  ('mulop -> OPERATORS','mulop',1,'p_expressions_mulop','parser.py',154),
  ('if_stmt -> KEYWORDS OPERATORS cond OPERATORS decl stmt_list else_part KEYWORDS','if_stmt',8,'p_complex_if_stmt','parser.py',158),
  ('else_part -> KEYWORDS decl stmt_list','else_part',3,'p_complex_else_part','parser.py',161),
  ('else_part -> empty','else_part',1,'p_complex_else_part','parser.py',162),
  ('cond -> KEYWORDS decl stmt_list','cond',3,'p_complex_cond','parser.py',165),
  ('cond -> empty','cond',1,'p_complex_cond','parser.py',166),
  ('while_stmt -> KEYWORDS OPERATORS cond OPERATORS decl stmt_list KEYWORDS','while_stmt',7,'p_whilestatement_while_stmt','parser.py',171),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',176),
]
